namespace FlazorTemplate.Authorization.Token
{
    public interface ITokenHandler
    {
        /// <summary>
        /// Generates a 
        /// </summary>
        /// <param name="emailAddress"></param>
        /// <param name="validFor"></param>
        /// <returns></returns>
        (string ott, string uid) GenerateOneTimeToken(string emailAddress, int validFor = 15);

        /// <summary>
        /// Verifies that a one-time token generated by <see cref="GenerateOneTimeToken"/> is valid.
        /// </summary>
        /// <param name="ottToken"></param>
        /// <returns></returns>
        (string email, string uid, bool status, string errtext) VerifyOneTimeToken(string ottToken);
    }
}
